#The probability of the item getting duped once the item frame is hit.
#100 and above means that every item will get duped. 0 will effectively disable this Module.

#If this is at 100% it will break the economy of your server it is recommended to set it to 50% or less
probability-percentage: 100